config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :events do
    resources :participations, only: [:create, :destroy]
  end

  root to: "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  PER_PAGE = 5.freeze
  DEFAULT_DIR = "desc".freeze
  DEFAULT_SORT = "id".freeze
  DEFAULT_SEARCH = "".freeze

  belongs_to :user
  has_many :participations, dependent: :destroy
  has_many :participants, through: :participations, source: :user

  validates :name, presence: true, length: { maximum: 255 }
  validates :description, presence: true
  validates :event_date_time, presence: true
  validates :location, presence: true, length: { maximum: 255 }
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :requirements, presence: true
  validate :event_date_time_in_future

  scope :not_current_user_ordered_with_ransack, ->(user_id, sort = DEFAULT_SORT, direction = DEFAULT_DIR, search = DEFAULT_SEARCH) {
    includes(:user)
      .where.not(user_id: user_id)
      .order("#{sort_column(sort)} #{sort_direction(direction)}")
      .ransack(search)
  }

  def self.ransackable_attributes(auth_object = nil)
    %w[id name event_date_time capacity]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end

  def self.sort_column(sort_value)
    %w[event_date_time name location capacity].include?(sort_value) ? sort_value : DEFAULT_SORT
  end

  def self.sort_direction(direction_value)
    %w[asc desc].include?(direction_value) ? direction_value : DEFAULT_DIR
  end

  private

  def event_date_time_in_future
    if event_date_time.present? && event_date_time <= Time.current
      errors.add(:event_date_time, I18n.t("activerecord.errors.models.event.attributes.event_date_time.time_in_pass"))
    end
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user_id, uniqueness: { scope: :event_id, message: "ya está registrado en este evento" }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable

  has_many :events, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :participated_events, through: :participations, source: :event

  def events_ordered_with_ransack(sort = Event::DEFAULT_SORT, direction = Event::DEFAULT_DIR, search = Event::DEFAULT_SEARCH)
    events
      .includes(:user)
      .order("#{Event.sort_column(sort)} #{Event.sort_direction(direction)}")
      .ransack(search)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    events_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user_event, only: %i[ edit update destroy ]
  before_action :check_event, only: %i[ show ]

  # GET /events
  def index
    if params[:all] == "true"
      @q = Event.not_current_user_ordered_with_ransack(current_user.id, params[:sort], params[:direction], params[:q])
      if params[:participation_filter] == "participating"
        @events = @q.result(distinct: true).joins(:participants).where(participations: { user_id: current_user.id }).page(params[:page]).per(Event::PER_PAGE)
      elsif params[:participation_filter] == "not_participating"
        @events = @q.result(distinct: true).where.not(id: current_user.participations.select(:event_id)).page(params[:page]).per(Event::PER_PAGE)
      else
        @events = @q.result(distinct: true).page(params[:page]).per(Event::PER_PAGE)
      end
    else
      @q = current_user.events_ordered_with_ransack(params[:sort], params[:direction], params[:q])
      @events = @q.result(distinct: true).page(params[:page]).per(Event::PER_PAGE)
    end


    respond_to do |format|
      format.html
      format.turbo_stream
      format.js
    end
  end

  # GET /events/1 or /events/1.json
  def show
    @all = params[:all] || false
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
    @view = params[:view] || "list"
    @back_path = @view == "show" ? event_path(@event) : events_path
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: I18n.t('controllers.events.created.success') }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: I18n.t('controllers.events.updated.success') }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!
    respond_to do |format|
      format.html { redirect_to events_url, notice: I18n.t('controllers.events.destroyed.success') }
      format.json { head :no_content }
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :event_date_time, :location, :capacity, :requirements, :user_id)
  end

  def check_user_event
    @event = current_user.events.find_by(id: params[:id])
    redirect_to events_path, notice: I18n.t('controllers.events.manage.not_auth') if @event.nil?
  end

  def check_event
    @event = Event.find_by(id: params[:id])
    redirect_to events_path, notice: I18n.t('controllers.events.manage.not_auth') if @event.nil?
  end

end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :authenticate_user!

  def create
    @event = Event.find(params[:event_id])
    @participation = @event.participations.build(user: current_user)

    respond_to do |format|
      if @participation.save
        format.js
        format.html { redirect_to events_path(all: true), notice: "Te has registrado en el evento exitosamente." }
      else
        format.js { render 'create_error' }
        format.html { redirect_to events_path(all: true), alert: "No puedes registrarte dos veces en el mismo evento." }
      end
    end
  end

  def destroy
    @event = Event.find(params[:event_id])
    @participation = @event.participations.find_by(user: current_user)
    respond_to do |format|
      if @participation
        @participation.destroy
        format.js
        format.html { redirect_to events_path(all: true), notice: "Has cancelado tu registro en el evento." }
      else
        format.js { render 'destroy_error' }
        format.html { redirect_to events_path(all: true), alert: "No estás registrado en este evento." }
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
# app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :check_captcha, only: [:create]

  def check_captcha
    unless verify_recaptcha
      self.resource = resource_class.new sign_up_params
      resource.validate # Look for any other validation errors besides reCAPTCHA
      set_minimum_password_length
      respond_with_navigational(resource) do
        flash.discard(:recaptcha_error) # Discard flash to avoid showing it on the next page reload
        render :new
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def long_formatted_date_time(date_time)
    date_time.strftime("%d/%m/%Y %H:%M")
  rescue StandardError => e
    "Fecha no válida"
  end

  def col_size(all = "false")
    all == "true" ? "3" : "4"
  end
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>" class="card shadow-sm mb-4">
  <div class="card-body">

    <div class="row">
       <div class="col-md-6 mb-3">
        <div class="row">
          <div class="col-md-12 mb-3">
            <h2 class="card-title">
              <strong><%= event.name %></strong>
            </h2>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12 mb-3">
            <p class="card-text">
              <%= event.description.capitalize %>
            </p>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <p class="card-text">
              <strong>Fecha y hora:</strong>
            </p>
            <p class="card-text">
              <%= long_formatted_date_time(event.event_date_time) %>
            </p>            
          </div>

          <div class="col-md-6 mb-3">
            <p class="card-text">
              <strong>Ubicación:</strong>
            </p>
            <p class="card-text">
              <%= event.location %>
            </p>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <p class="card-text">
              <strong>Capacidad:</strong>
            </p>
            <p class="card-text">
              <%= event.capacity %>
            </p>
          </div>

          <div class="col-md-6 mb-3">
            <p class="card-text">
              <strong>Requerimientos:</strong>
            </p>
            <p class="card-text">
              <%= event.requirements %>
            </p>
          </div>
        </div>



      </div>

      <div class="col-md-6 mb-3 text-center">
        <%= image_tag('no-image.jpg', alt: 'No Image', class: 'brand') %>
      </div>
    </div>




  </div>
</div>

app/views/events/_events_list.html.erb
<% if @events.blank? %>
  <div>No hay eventos registrados aún.</div>
<% else %>
  <div class="table-container p-0 pb-4">
    <table class="table table-striped mb-4">
      <thead>
        <tr>
          <th class="pl-3"><%= sort_link(@q, :id, "N°", {all: params[:all], data: {turbo: false}}) %></th>
          <th><%= sort_link(@q, :name, "Nombre", {all: params[:all], data: {turbo: false}}) %></th>
          <th><%= sort_link(@q, :event_date_time, "Fecha y Hora", {all: params[:all], data: {turbo: false}}) %></th>
          <th><%= sort_link(@q, :capacity, "Capacidad", {all: params[:all], data: {turbo: false}}) %></th>
          <th class="text-right">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr id="<%= dom_id(event) %>" class="row-event-<%= event.id %>">
            <td class="pl-3"><%= event.id %></td>
            <td><%= event.name %></td>
            <td><%= long_formatted_date_time(event.event_date_time) %></td>
            <td><%= event.capacity %></td>
            <td class="text-right actions-column">
              <% if params[:all] %>
                <%= render 'participations/button', event: event %>
              <% else %>
                <%= link_to event_path(event), class: "btn btn-info btn-sm btn-icon mr-2", data: { turbo: false } do %>
                  <i class="fa fa-eye text-white"></i>
                <% end %>
                <%= link_to edit_event_path(event), class: "btn btn-edit btn-sm btn-icon mr-2", data: { turbo: false } do %>
                  <i class="fa fa-edit"></i>
                <% end %>
                <%= button_to event_path(event), method: :delete, data: { confirm: I18n.t('events.delete.confirm', name: event.name, number: event.id), turbo: false }, class: "btn btn-light btn-sm btn-icon d-inline-block" do %>
                  <i class="fa fa-trash"></i>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="d-flex justify-content-center">
      <%= paginate events, params: { all: params[:all] } %>
    </div>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, class: "form-box shadow-sm") do |form| %>
  <% if event.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(event.errors.count, "error") %> prohibieron que este evento se guardara:</h2>
      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mt-3">
    <div class="col-md-12">
      <div class="form-group">
        <%= form.label :name, class: "d-block font-weight-bold mb-2" %>
        <%= form.text_field :name, class: "form-control", placeholder: "Nombre del evento" %>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :location, class: "d-block font-weight-bold mb-2" %>
        <%= form.text_field :location, class: "form-control", placeholder: "Ubicación del evento" %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :event_date_time, class: "d-block font-weight-bold mb-2" %>
        <%= form.datetime_field :event_date_time, class: "form-control" %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :capacity, class: "d-block font-weight-bold mb-2" %>
        <%= form.number_field :capacity, class: "form-control", placeholder: "Capacidad del evento" %>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-12">
      <div class="form-group">
        <%= form.label :description, class: "d-block font-weight-bold mb-2" %>
        <%= form.text_area :description, class: "form-control", placeholder: "Descripción del evento" %>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-12">
      <div class="form-group">
        <%= form.label :requirements, class: "d-block font-weight-bold mb-2" %>
        <%= form.text_area :requirements, class: "form-control", placeholder: "Requisitos del evento" %>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-9"></div>
    <div class="col-md-3">
      <div class="form-group mt-3">
        <%= form.submit button_name, class: "btn btn-primary btn-block btn-action-custome"%>
      </div>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="d-flex justify-content-between align-items-center box-title-buttons">
  <div class="flex-grow-1">
    <h1 class="mb-0 font-weight-bold">Edición del evento N° <%= @event.id %></h1>
  </div>
  <div>
    <%= link_to @back_path, class: "btn btn-secondary btn-icon btn-action-custome", data: { turbo: false } do %>
      <i class="fa fa-arrow-left mr-2"></i> Volver
    <% end %>
  </div>
</div>

<%= render "form", event: @event, button_name: I18n.t("events.form.button.edit") %>

app/views/events/index.html.erb
<div class="d-flex justify-content-between align-items-center box-title-buttons">
  <div class="flex-grow-1">
    <h1 class="mb-0 font-weight-bold">
      <% if params[:all] %>
        Todos los Eventos
      <% else %>
        Mis Eventos
      <% end %>
    </h1>
  </div>
  <div>
    <%= link_to 'Nuevo Evento', new_event_path, class: 'btn btn-primary btn-action-custome', data: { turbo: false } unless params[:all] %>
  </div>
</div>

<%= search_form_for @q, url: events_path, method: :get, class: "search-box", data: { turbo_frame: "events" } do |f| %>
  <%= hidden_field_tag :all, params[:all] %>
  <div class="row">
    <div class="col-md-<%= col_size(params[:all]) %>">
      <%= f.label :name_cont, "Nombre", class: "font-weight-bold mb-2" %>
      <%= f.search_field :name_cont, placeholder: "Nombre del evento", class: "form-control" %>
    </div>
    <div class="col-md-<%= col_size(params[:all]) %>">
      <%= f.label :event_date_time_range, "Rango de fecha y hora", class: "font-weight-bold mb-2" %>
      <div class="d-flex">
        <%= f.datetime_field :event_date_time_gteq, placeholder: "Inicio", class: "form-control me-2"%>
        <%= f.datetime_field :event_date_time_lteq, placeholder: "Fin", class: "form-control" %>
      </div>
    </div>
    <div class="col-md-2">
      <%= f.label :capacity_range, "Rango de Cap.", class: "font-weight-bold mb-2" %>
      <div class="d-flex">
        <%= f.number_field :capacity_gteq, placeholder: "Mín", class: "form-control me-2" %>
        <%= f.number_field :capacity_lteq, placeholder: "Máx", class: "form-control" %>
      </div>
    </div>
    <% if params[:all] == "true" %>
      <div class="col-md-2">
        <%= label_tag :participation_filter, "Filtrar por participación", class: "font-weight-bold mb-2" %>
        <%= select_tag :participation_filter, options_for_select([["Todos", "all"], ["Participando", "participating"], ["No Participando", "not_participating"]], params[:participation_filter]), class: "form-control" %>
      </div>
    <% end %>

    <div class="col-md-1 d-flex align-items-center btn-box">
      <%= button_tag "Limpiar", type: "reset", class: "btn btn-secondary w-100 btn-action-custome btn-reset" %>
    </div>    
    <div class="col-md-1 d-flex align-items-center btn-box">
      <%= f.submit "Buscar", class: "btn btn-primary w-100 btn-action-custome" %>
    </div>
  </div>
<% end %>

<turbo-frame id="events" class="events_list">
  <%= render 'events_list', events: @events %>
</turbo-frame>

app/views/events/index.js.erb
$('#events_list').html("<%= j render('events_list', events: @events) %>");

app/views/events/new.html.erb
<div class="d-flex justify-content-between align-items-center box-title-buttons">
  <div class="flex-grow-1">
    <h1 class="mb-0 font-weight-bold">Nuevo Evento </h1>
  </div>
  <div>
    <%= link_to events_path, class: "btn btn-secondary btn-icon btn-action-custome", data: { turbo: false } do %>
      <i class="fa fa-arrow-left mr-2"></i> Volver
    <% end %>
  </div>
</div>

<%= render "form", event: @event, button_name: I18n.t("events.form.button.create") %>

app/views/events/show.html.erb
<div class="d-flex justify-content-between align-items-center box-title-buttons">
  <div class="flex-grow-1">
    <h1 class="mb-0 font-weight-bold">Evento N° <%= @event.id %></h1>
  </div>

  <% if @event.user_id == current_user.id %>
    <div class="mr-2">
      <%= link_to edit_event_path(@event, view: "show"), class: "btn btn-edit btn-sm btn-icon btn-action-custome mr-2", data: { turbo: false } do %>
        <i class="fa fa-edit"></i> Editar
      <% end %>
    </div>
    <div class="mr-2">
      <%= button_to event_path(@event), method: :delete, data: { confirm: I18n.t('events.delete.confirm', name: @event.name, number: @event.id), turbo: false }, class: "btn btn-light btn-sm btn-icon d-inline-block btn-action-custome mr-2" do %>
        <i class="fa fa-trash"></i> Eliminar
      <% end %>
    </div>
  <% else %>
    <% if current_user.participated_events.include?(@event) %>
      <div class="mr-2">
        <%= button_to event_participation_path(@event, current_user.participations.find_by(event: @event)), method: :delete, data: { turbo: false }, class: "btn btn-light btn-sm btn-icon btn-action-custome mr-2" do %>
          <i class="fa fa-times"></i> No participar
        <% end %>
      </div>
    <% else %>
      <div class="mr-2">
        <%= button_to event_participations_path(@event), method: :post, data: { turbo: false }, class: "btn btn-success btn-sm btn-icon d-inline-block btn-action-custome mr-2" do %>
          <i class="fa fa-plus"></i> Participar
        <% end %>
      </div>
    <% end %>
  <% end %>

  <div>
    <%= link_to events_path(all: true), class: "btn btn-secondary btn-icon btn-action-custome", data: { turbo: false } do %>
      <i class="fa fa-arrow-left mr-2"></i> Volver
    <% end %>
  </div>
</div>

<%= render "event", event: @event %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="flash-message alert alert-<%= key == "notice" ? "success" : "danger" %> alert-dismissible fade show p-1" role="alert">
    <%= value %>
  </div>
<% end %>

app/views/layouts/_not_signed.html.erb
<div class="container-fluid">
  <main class="main-not-signed-content">
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </main>
</div>

app/views/layouts/_sidebar.html.erb
<div class="d-flex flex-column h-100 w-100">
  <ul class="nav flex-column flex-grow-1 ul-menu">
    <li class="nav-item">
      <%= link_to image_tag('title-lemontech.png', alt: 'LemontechEvents', class: 'brand'), root_path %>
    </li>
    <li class="nav-item li-text">
      <%= link_to 'Mis Eventos', events_path, class: "nav-link" %>
    </li>
  </ul>
  <ul class="nav flex-column">
    <li class="nav-item mt-auto li-logout">
      <%= link_to destroy_user_session_path, class: "nav-link" do %>
          Cerrar Sesión  <i class="fa fa-sign-out"></i> 
      <% end %>

    </li>
  </ul>
</div>

app/views/layouts/_signed.html.erb
<nav class="navbar navbar-expand-lg bg-white p-0">
  <div class="container-fluid">
    <span class="navbar-brand">
      <%= link_to root_path, data: { turbo: false } do %>
        <%= image_tag "title-lemontech-color.svg", alt: "LemontechEvents", class: "d-inline-block align-text-top" %>
      <% end %>
    </span>
    <ul class="navbar-nav ms-auto d-flex align-items-center">
      <li class="nav-item d-flex align-items-center">
        <% if params[:all] %>
          <%= link_to events_path, class: "nav-link" do %>
            <span>Mis Eventos</span>
          <% end %>
        <% else %>
          <%= link_to events_path(all: true), class: "nav-link" do %>
            <span>Eventos</span>
          <% end %>
        <% end %>
      </li>
      <li class="nav-item d-flex align-items-center">
        <%= link_to edit_user_registration_path, class: "nav-link d-flex align-items-center profile-link", data: { turbo: false } do %>
          <%= image_tag "profile-blank.png", alt: "Perfil", class: "rounded-circle", width: 30, height: 30 %>
          <span>Perfil</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to 'Cerrar Sesión', destroy_user_session_path, data: { turbo: false }, class: "nav-link logout-link" %>
      </li>
    </ul>
  </div>
</nav>

<div class="container-fluid">
  <main class="main-content p-4 pt-0 pb-0">
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LemontechEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <meta name="turbo-prefetch" content="false">
  </head>

  <body>
    <main class="flex-grow-1">
      <% if user_signed_in? %>
        <%= render 'layouts/signed' %>
      <% else %>
        <%= render 'layouts/not_signed' %>
      <% end %>
    </main>

    <footer class="text-center py-3">
      <p>&copy; <%= Time.now.year %> Génesis González (contacto: <a href="mailto:genesisgonza05@gmail.com">genesisgonza05@gmail.com</a>)</p>
    </footer>
  </body>
</html>

app/views/participations/_button.html.erb
<%= link_to event_path(event, all: true), class: "btn btn-info btn-sm btn-icon mr-2", data: { turbo: false } do %>
  <i class="fa fa-eye text-white"></i>
<% end %>

<% if current_user.participated_events.include?(event) %>
  <%= button_to event_participation_path(event, current_user.participations.find_by(event: event)), method: :delete, remote: true, data: { turbo: false }, class: "btn btn-danger btn-sm btn-icon mr-2" do %>
    <i class="fa fa-times text-white"></i>
  <% end %>
<% else %>
  <%= button_to event_participations_path(event), method: :post, remote: true, data: { turbo: false }, class: "btn btn-success btn-sm btn-icon mr-2" do %>
    <i class="fa fa-plus text-white"></i>
  <% end %>
<% end %>

app/views/participations/create.js.erb
$("#<%= dom_id(@event) %> .actions-column").html("<%= j render 'participations/button', event: @event %>");

app/views/participations/destroy.js.erb
$("#<%= dom_id(@event) %> .actions-column").html("<%= j render 'participations/button', event: @event %>");